author: Callum McColl
theme: fullwidth
github_url: https://github.com/mipalgu/swift_GUCoordinates
github_file_prefix: https://github.com/mipalgu/swift_GUCoordinates/tree/main
root_url: https://mipalgu.github.io/swift_GUCoordinates/

exclude:
    - Sources/*/gu_*.swift
    - swift_GUCoordinates/Sources/*/gu_*.swift
