name: Jazzy Documentation

on:
  push:
    branches: [ main ]

jobs:

  exec-jazzy:
    runs-on: macos-11

    steps:
    - name: Install Ninja
      run: brew install ninja

    - name: Install CMake
      run: brew install cmake

    - name: Clone gu_util
      uses: actions/checkout@v2
      with:
        repository: mipalgu/gu_util
        path: gu_util

    - name: Install gu_util
      run: |
        cd gu_util
        mkdir build
        cd build
        cmake -G Ninja ..
        ninja
        ninja install
        cd ../..

    - name: Clone guunits
      uses: actions/checkout@v2
      with:
        repository: mipalgu/guunits
        path: guunits

    - name: Install guunits
      run: |
        cd guunits/guunits
        mkdir build
        cd build
        cmake -G Ninja ..
        ninja
        ninja install
        cd ../../..
    
    - name: Clone gucoordinates
      uses: actions/checkout@v2
      with:
        repository: mipalgu/gucoordinates
        path: gucoordinates

    - name: Install gucoordinates
      run: |
        cd gucoordinates/gucoordinates
        mkdir build
        cd build
        cmake -G Ninja ..
        ninja
        ninja install
        cd ../../..

    - name: Clone Repository 
      uses: actions/checkout@v2
      with:
        repository: mipalgu/swift_GUCoordinates
        path: swift_GUCoordinates
      
    - name: Cd into swift_GUCoordinates
      run: |
        pwd

    - name: Jazzy Action
      uses: sersoft-gmbh/swifty-docs-action@v1.2.0
      with:
        output: docs

    - name: Pages Deployment
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
