name: Jazzy Documentation

on:
  push:
    branches: [ main ]

jobs:
  exec-jazzy:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    
    - name: Jazzy Action
      uses: sersoft-gmbh/swifty-docs-action@v1
      with:
        output: docs

    - name: Pages Deployment
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
